version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "${PORT:-4000}:4000"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-4000}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - AUTHENTICATION_HOST=localhost
      - AUTHENTICATION_PORT=4001
      - USERS_HOST=localhost
      - USERS_PORT=4002
    depends_on:
      - authentication
      - users
    network_mode: host

  authentication:
    build:
      context: .
      dockerfile: Dockerfile.authentication
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    network_mode: host

  users:
    build:
      context: .
      dockerfile: Dockerfile.users
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    network_mode: host
